DROP FUNCTION insert_student;
DROP FUNCTION insert_building(text, text, integer, integer);
DROP FUNCTION insert_building;
DROP FUNCTION insert_locker;
DROP FUNCTION insert_department;
DROP FUNCTION insert_employee;
DROP FUNCTION insert_faculty;
DROP FUNCTION insert_club;
DROP FUNCTION insert_course;
DROP FUNCTION insert_section;
DROP FUNCTION delete_row;
DROP FUNCTION register_section;
DROP FUNCTION join_club;
DROP FUNCTION show_course_history;
DROP FUNCTION calc_student_gpa;